### ISSUE TITLE
Getting the test suite to run

### ISSUE THREAD

**Issue by felixge** [nodejitsu/node-cloudfiles#3]
I just tired to get the test suite to run, but unfortunately my output looks like this:

```
vows --verbose
The 'sys' module is now called 'util'. It should have a similar interface.
vows bin argv []
vows bin options { reporter: 'dot-matrix', matcher: /.*/ }
vows bin discovering folder structure
vows bin discovered ./test
vows runner loading [
    '/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/authentication-test',
    '/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/container-destroy-test',
    '/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/container-test',
    '/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/helpers',
    '/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/mime-test',
    '/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/storage-object-metadata-test',
    '/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/storage-object-test'
]
vows runner running node-cloudfiles/authentication ···· 
vows runner running node-cloudfiles/containers · ·· 
vows runner running node-cloudfiles/containers · ·· ······ · · · 
vows runner running undefined 
/Users/felix/.node_libraries/.npm/vows/0.5.2/package/bin/vows:330
            suite.run(options, function (result) {
                  ^
TypeError: Object function (container) {
  assert.instanceOf(container, cloudfiles.Container);
  assert.isNotNull(container.name);
  assert.isNotNull(container.count);
  assert.isNotNull(container.bytes);
} has no method 'run'
    at run (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/bin/vows:330:19)
    at /Users/felix/.node_libraries/.npm/vows/0.5.2/package/bin/vows:334:17
    at run (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/suite.js:267:46)
    at EventEmitter.<anonymous> (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/suite.js:260:25)
    at EventEmitter.emit (events.js:31:15)
    at Object.tryEnd (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/suite.js:307:23)
    at EventEmitter.<anonymous> (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows.js:74:14)
    at EventEmitter.emit (events.js:41:20)
    at /Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/context.js:29:52
    at /Users/felix/.node_libraries/.npm/vo
```

I also had to add this to the prototype of config.js in order to get things to run at all. What is the cache used for?

```
  cache: {
    path: __dirname
  },
```

Anyway, let me know what you get when running the test suite so I can continue debugging this.

--fg

**Comment by indexzero** [comment]
Not all the files in the /test directory are vows suites, which I believe is why you're seeing that message since you're just running 

<pre>
vows --verbose
</pre>


You should run vows on all the *-test.js files like so:

<pre>
vows test/*-test.js --spec
</pre>


The cache directory is used to stream files to local disk. I ran into an issue with node core apis when pumping a response stream to a file stream. Check out this sample:

http://github.com/indexzero/node-experiments/blob/master/targz/targz.js

So right now when you call .getFiles() it downloads the file locally to the cache directory puts that local path in the instance of the StorageObject that is returned in the callback.

**Comment by felixge** [comment]
Ok, this is looking better now, but I'm still getting an error at the end. Let me know if you have any idea:

```
$ vows test/*-test.js --spec
The 'sys' module is now called 'util'. It should have a similar interface.

♢ node-cloudfiles/authentication

  The node-cloudfiles client
    ✓ should have core methods defined
  The node-cloudfiles client with a valid username and api key
    ✓ should respond with 204 and appropriate headers
    ✓ should update the config with appropriate urls
  The node-cloudfiles client with an invalid username and api key
    ✓ should respond with 401

♢ node-cloudfiles/containers

  The node-cloudfiles client when authenticated
    ✓ should return with 204
  The node-cloudfiles client the destroyContainer() method when deleting test_cdn_container
    ✓ should return true
  The node-cloudfiles client the destroyContainer() method when deleting test_container
    ✓ should return true

♢ node-cloudfiles/containers

  The node-cloudfiles client when authenticated
    ✓ should return with 204
  The node-cloudfiles client the createContainer() method when creating a CDN-enabled container
    ✓ should return a valid container
  The node-cloudfiles client the createContainer() method when creating a container
    ✓ should return a valid container
  The node-cloudfiles client the getContainers() method when requesting non-CDN containers
    ✓ should return a list of containers
  The node-cloudfiles client the getContainer() method when requesting CDN container with an invalid CDN container
    ✓ should respond with an error
  The node-cloudfiles client the getContainer() method when requesting CDN container with a valid CDN container
    ✓ should return a valid container
  The node-cloudfiles client the getContainer() method when requesting non-CDN container
    ✓ should return a valid container
  The node-cloudfiles client the getContainers() method when requesting CDN containers
    ✓ should return a list of containers
  The node-cloudfiles client the createContainer() method when creating a container that already exists
    ✓ should return a valid container
  The node-cloudfiles client an instance of a Container object the addFile() method
    ✓ should respond with true
  The node-cloudfiles client an instance of a Container object the getFiles() method
    ✓ should response with a list of files
  The node-cloudfiles client an instance of a Container object the removeFile() method
    ✓ should response with true

♢ cloudfiles/mime

  When using the node-cloudfiles client the mime type module when passed a .3gp file
    ✓ should response with video/3gpp mimetype
  When using the node-cloudfiles client the mime type module when passed a .a file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .ai file
    ✓ should response with application/postscript mimetype
  When using the node-cloudfiles client the mime type module when passed a .aif file
    ✓ should response with audio/x-aiff mimetype
  When using the node-cloudfiles client the mime type module when passed a .aiff file
    ✓ should response with audio/x-aiff mimetype
  When using the node-cloudfiles client the mime type module when passed a .asc file
    ✓ should response with application/pgp-signature mimetype
  When using the node-cloudfiles client the mime type module when passed a .asf file
    ✓ should response with video/x-ms-asf mimetype
  When using the node-cloudfiles client the mime type module when passed a .asm file
    ✓ should response with text/x-asm mimetype
  When using the node-cloudfiles client the mime type module when passed a .asx file
    ✓ should response with video/x-ms-asf mimetype
  When using the node-cloudfiles client the mime type module when passed a .atom file
    ✓ should response with application/atom+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .au file
    ✓ should response with audio/basic mimetype
  When using the node-cloudfiles client the mime type module when passed a .avi file
    ✓ should response with video/x-msvideo mimetype
  When using the node-cloudfiles client the mime type module when passed a .bat file
    ✓ should response with application/x-msdownload mimetype
  When using the node-cloudfiles client the mime type module when passed a .bin file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .bmp file
    ✓ should response with image/bmp mimetype
  When using the node-cloudfiles client the mime type module when passed a .bz2 file
    ✓ should response with application/x-bzip2 mimetype
  When using the node-cloudfiles client the mime type module when passed a .c file
    ✓ should response with text/x-c mimetype
  When using the node-cloudfiles client the mime type module when passed a .cab file
    ✓ should response with application/vnd.ms-cab-compressed mimetype
  When using the node-cloudfiles client the mime type module when passed a .cc file
    ✓ should response with text/x-c mimetype
  When using the node-cloudfiles client the mime type module when passed a .chm file
    ✓ should response with application/vnd.ms-htmlhelp mimetype
  When using the node-cloudfiles client the mime type module when passed a .class file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .com file
    ✓ should response with application/x-msdownload mimetype
  When using the node-cloudfiles client the mime type module when passed a .conf file
    ✓ should response with text/plain mimetype
  When using the node-cloudfiles client the mime type module when passed a .cpp file
    ✓ should response with text/x-c mimetype
  When using the node-cloudfiles client the mime type module when passed a .crt file
    ✓ should response with application/x-x509-ca-cert mimetype
  When using the node-cloudfiles client the mime type module when passed a .css file
    ✓ should response with text/css mimetype
  When using the node-cloudfiles client the mime type module when passed a .csv file
    ✓ should response with text/csv mimetype
  When using the node-cloudfiles client the mime type module when passed a .cxx file
    ✓ should response with text/x-c mimetype
  When using the node-cloudfiles client the mime type module when passed a .deb file
    ✓ should response with application/x-debian-package mimetype
  When using the node-cloudfiles client the mime type module when passed a .der file
    ✓ should response with application/x-x509-ca-cert mimetype
  When using the node-cloudfiles client the mime type module when passed a .diff file
    ✓ should response with text/x-diff mimetype
  When using the node-cloudfiles client the mime type module when passed a .djv file
    ✓ should response with image/vnd.djvu mimetype
  When using the node-cloudfiles client the mime type module when passed a .djvu file
    ✓ should response with image/vnd.djvu mimetype
  When using the node-cloudfiles client the mime type module when passed a .dll file
    ✓ should response with application/x-msdownload mimetype
  When using the node-cloudfiles client the mime type module when passed a .dmg file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .doc file
    ✓ should response with application/msword mimetype
  When using the node-cloudfiles client the mime type module when passed a .dot file
    ✓ should response with application/msword mimetype
  When using the node-cloudfiles client the mime type module when passed a .dtd file
    ✓ should response with application/xml-dtd mimetype
  When using the node-cloudfiles client the mime type module when passed a .dvi file
    ✓ should response with application/x-dvi mimetype
  When using the node-cloudfiles client the mime type module when passed a .ear file
    ✓ should response with application/java-archive mimetype
  When using the node-cloudfiles client the mime type module when passed a .eml file
    ✓ should response with message/rfc822 mimetype
  When using the node-cloudfiles client the mime type module when passed a .eps file
    ✓ should response with application/postscript mimetype
  When using the node-cloudfiles client the mime type module when passed a .exe file
    ✓ should response with application/x-msdownload mimetype
  When using the node-cloudfiles client the mime type module when passed a .f file
    ✓ should response with text/x-fortran mimetype
  When using the node-cloudfiles client the mime type module when passed a .f77 file
    ✓ should response with text/x-fortran mimetype
  When using the node-cloudfiles client the mime type module when passed a .f90 file
    ✓ should response with text/x-fortran mimetype
  When using the node-cloudfiles client the mime type module when passed a .flv file
    ✓ should response with video/x-flv mimetype
  When using the node-cloudfiles client the mime type module when passed a .for file
    ✓ should response with text/x-fortran mimetype
  When using the node-cloudfiles client the mime type module when passed a .gem file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .gemspec file
    ✓ should response with text/x-script.ruby mimetype
  When using the node-cloudfiles client the mime type module when passed a .gif file
    ✓ should response with image/gif mimetype
  When using the node-cloudfiles client the mime type module when passed a .gz file
    ✓ should response with application/x-gzip mimetype
  When using the node-cloudfiles client the mime type module when passed a .h file
    ✓ should response with text/x-c mimetype
  When using the node-cloudfiles client the mime type module when passed a .hh file
    ✓ should response with text/x-c mimetype
  When using the node-cloudfiles client the mime type module when passed a .htm file
    ✓ should response with text/html mimetype
  When using the node-cloudfiles client the mime type module when passed a .html file
    ✓ should response with text/html mimetype
  When using the node-cloudfiles client the mime type module when passed a .ico file
    ✓ should response with image/vnd.microsoft.icon mimetype
  When using the node-cloudfiles client the mime type module when passed a .ics file
    ✓ should response with text/calendar mimetype
  When using the node-cloudfiles client the mime type module when passed a .ifb file
    ✓ should response with text/calendar mimetype
  When using the node-cloudfiles client the mime type module when passed a .iso file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .jar file
    ✓ should response with application/java-archive mimetype
  When using the node-cloudfiles client the mime type module when passed a .java file
    ✓ should response with text/x-java-source mimetype
  When using the node-cloudfiles client the mime type module when passed a .jnlp file
    ✓ should response with application/x-java-jnlp-file mimetype
  When using the node-cloudfiles client the mime type module when passed a .jpeg file
    ✓ should response with image/jpeg mimetype
  When using the node-cloudfiles client the mime type module when passed a .jpg file
    ✓ should response with image/jpeg mimetype
  When using the node-cloudfiles client the mime type module when passed a .js file
    ✓ should response with application/javascript mimetype
  When using the node-cloudfiles client the mime type module when passed a .json file
    ✓ should response with application/json mimetype
  When using the node-cloudfiles client the mime type module when passed a .log file
    ✓ should response with text/plain mimetype
  When using the node-cloudfiles client the mime type module when passed a .m3u file
    ✓ should response with audio/x-mpegurl mimetype
  When using the node-cloudfiles client the mime type module when passed a .m4v file
    ✓ should response with video/mp4 mimetype
  When using the node-cloudfiles client the mime type module when passed a .man file
    ✓ should response with text/troff mimetype
  When using the node-cloudfiles client the mime type module when passed a .mathml file
    ✓ should response with application/mathml+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .mbox file
    ✓ should response with application/mbox mimetype
  When using the node-cloudfiles client the mime type module when passed a .mdoc file
    ✓ should response with text/troff mimetype
  When using the node-cloudfiles client the mime type module when passed a .me file
    ✓ should response with text/troff mimetype
  When using the node-cloudfiles client the mime type module when passed a .mid file
    ✓ should response with audio/midi mimetype
  When using the node-cloudfiles client the mime type module when passed a .midi file
    ✓ should response with audio/midi mimetype
  When using the node-cloudfiles client the mime type module when passed a .mime file
    ✓ should response with message/rfc822 mimetype
  When using the node-cloudfiles client the mime type module when passed a .mml file
    ✓ should response with application/mathml+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .mng file
    ✓ should response with video/x-mng mimetype
  When using the node-cloudfiles client the mime type module when passed a .mov file
    ✓ should response with video/quicktime mimetype
  When using the node-cloudfiles client the mime type module when passed a .mp3 file
    ✓ should response with audio/mpeg mimetype
  When using the node-cloudfiles client the mime type module when passed a .mp4 file
    ✓ should response with video/mp4 mimetype
  When using the node-cloudfiles client the mime type module when passed a .mp4v file
    ✓ should response with video/mp4 mimetype
  When using the node-cloudfiles client the mime type module when passed a .mpeg file
    ✓ should response with video/mpeg mimetype
  When using the node-cloudfiles client the mime type module when passed a .mpg file
    ✓ should response with video/mpeg mimetype
  When using the node-cloudfiles client the mime type module when passed a .ms file
    ✓ should response with text/troff mimetype
  When using the node-cloudfiles client the mime type module when passed a .msi file
    ✓ should response with application/x-msdownload mimetype
  When using the node-cloudfiles client the mime type module when passed a .odp file
    ✓ should response with application/vnd.oasis.opendocument.presentation mimetype
  When using the node-cloudfiles client the mime type module when passed a .ods file
    ✓ should response with application/vnd.oasis.opendocument.spreadsheet mimetype
  When using the node-cloudfiles client the mime type module when passed a .odt file
    ✓ should response with application/vnd.oasis.opendocument.text mimetype
  When using the node-cloudfiles client the mime type module when passed a .ogg file
    ✓ should response with application/ogg mimetype
  When using the node-cloudfiles client the mime type module when passed a .p file
    ✓ should response with text/x-pascal mimetype
  When using the node-cloudfiles client the mime type module when passed a .pas file
    ✓ should response with text/x-pascal mimetype
  When using the node-cloudfiles client the mime type module when passed a .pbm file
    ✓ should response with image/x-portable-bitmap mimetype
  When using the node-cloudfiles client the mime type module when passed a .pdf file
    ✓ should response with application/pdf mimetype
  When using the node-cloudfiles client the mime type module when passed a .pem file
    ✓ should response with application/x-x509-ca-cert mimetype
  When using the node-cloudfiles client the mime type module when passed a .pgm file
    ✓ should response with image/x-portable-graymap mimetype
  When using the node-cloudfiles client the mime type module when passed a .pgp file
    ✓ should response with application/pgp-encrypted mimetype
  When using the node-cloudfiles client the mime type module when passed a .pkg file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .pl file
    ✓ should response with text/x-script.perl mimetype
  When using the node-cloudfiles client the mime type module when passed a .pm file
    ✓ should response with text/x-script.perl-module mimetype
  When using the node-cloudfiles client the mime type module when passed a .png file
    ✓ should response with image/png mimetype
  When using the node-cloudfiles client the mime type module when passed a .pnm file
    ✓ should response with image/x-portable-anymap mimetype
  When using the node-cloudfiles client the mime type module when passed a .ppm file
    ✓ should response with image/x-portable-pixmap mimetype
  When using the node-cloudfiles client the mime type module when passed a .pps file
    ✓ should response with application/vnd.ms-powerpoint mimetype
  When using the node-cloudfiles client the mime type module when passed a .ppt file
    ✓ should response with application/vnd.ms-powerpoint mimetype
  When using the node-cloudfiles client the mime type module when passed a .ps file
    ✓ should response with application/postscript mimetype
  When using the node-cloudfiles client the mime type module when passed a .psd file
    ✓ should response with image/vnd.adobe.photoshop mimetype
  When using the node-cloudfiles client the mime type module when passed a .py file
    ✓ should response with text/x-script.python mimetype
  When using the node-cloudfiles client the mime type module when passed a .qt file
    ✓ should response with video/quicktime mimetype
  When using the node-cloudfiles client the mime type module when passed a .ra file
    ✓ should response with audio/x-pn-realaudio mimetype
  When using the node-cloudfiles client the mime type module when passed a .rake file
    ✓ should response with text/x-script.ruby mimetype
  When using the node-cloudfiles client the mime type module when passed a .ram file
    ✓ should response with audio/x-pn-realaudio mimetype
  When using the node-cloudfiles client the mime type module when passed a .rar file
    ✓ should response with application/x-rar-compressed mimetype
  When using the node-cloudfiles client the mime type module when passed a .rb file
    ✓ should response with text/x-script.ruby mimetype
  When using the node-cloudfiles client the mime type module when passed a .rdf file
    ✓ should response with application/rdf+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .roff file
    ✓ should response with text/troff mimetype
  When using the node-cloudfiles client the mime type module when passed a .rpm file
    ✓ should response with application/x-redhat-package-manager mimetype
  When using the node-cloudfiles client the mime type module when passed a .rss file
    ✓ should response with application/rss+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .rtf file
    ✓ should response with application/rtf mimetype
  When using the node-cloudfiles client the mime type module when passed a .ru file
    ✓ should response with text/x-script.ruby mimetype
  When using the node-cloudfiles client the mime type module when passed a .s file
    ✓ should response with text/x-asm mimetype
  When using the node-cloudfiles client the mime type module when passed a .sgm file
    ✓ should response with text/sgml mimetype
  When using the node-cloudfiles client the mime type module when passed a .sgml file
    ✓ should response with text/sgml mimetype
  When using the node-cloudfiles client the mime type module when passed a .sh file
    ✓ should response with application/x-sh mimetype
  When using the node-cloudfiles client the mime type module when passed a .sig file
    ✓ should response with application/pgp-signature mimetype
  When using the node-cloudfiles client the mime type module when passed a .snd file
    ✓ should response with audio/basic mimetype
  When using the node-cloudfiles client the mime type module when passed a .so file
    ✓ should response with application/octet-stream mimetype
  When using the node-cloudfiles client the mime type module when passed a .svg file
    ✓ should response with image/svg+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .svgz file
    ✓ should response with image/svg+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .swf file
    ✓ should response with application/x-shockwave-flash mimetype
  When using the node-cloudfiles client the mime type module when passed a .t file
    ✓ should response with text/troff mimetype
  When using the node-cloudfiles client the mime type module when passed a .tar file
    ✓ should response with application/x-tar mimetype
  When using the node-cloudfiles client the mime type module when passed a .tbz file
    ✓ should response with application/x-bzip-compressed-tar mimetype
  When using the node-cloudfiles client the mime type module when passed a .tci file
    ✓ should response with application/x-topcloud mimetype
  When using the node-cloudfiles client the mime type module when passed a .tcl file
    ✓ should response with application/x-tcl mimetype
  When using the node-cloudfiles client the mime type module when passed a .tex file
    ✓ should response with application/x-tex mimetype
  When using the node-cloudfiles client the mime type module when passed a .texi file
    ✓ should response with application/x-texinfo mimetype
  When using the node-cloudfiles client the mime type module when passed a .texinfo file
    ✓ should response with application/x-texinfo mimetype
  When using the node-cloudfiles client the mime type module when passed a .text file
    ✓ should response with text/plain mimetype
  When using the node-cloudfiles client the mime type module when passed a .tif file
    ✓ should response with image/tiff mimetype
  When using the node-cloudfiles client the mime type module when passed a .tiff file
    ✓ should response with image/tiff mimetype
  When using the node-cloudfiles client the mime type module when passed a .torrent file
    ✓ should response with application/x-bittorrent mimetype
  When using the node-cloudfiles client the mime type module when passed a .tr file
    ✓ should response with text/troff mimetype
  When using the node-cloudfiles client the mime type module when passed a .ttf file
    ✓ should response with application/x-font-ttf mimetype
  When using the node-cloudfiles client the mime type module when passed a .txt file
    ✓ should response with text/plain mimetype
  When using the node-cloudfiles client the mime type module when passed a .vcf file
    ✓ should response with text/x-vcard mimetype
  When using the node-cloudfiles client the mime type module when passed a .vcs file
    ✓ should response with text/x-vcalendar mimetype
  When using the node-cloudfiles client the mime type module when passed a .vrml file
    ✓ should response with model/vrml mimetype
  When using the node-cloudfiles client the mime type module when passed a .war file
    ✓ should response with application/java-archive mimetype
  When using the node-cloudfiles client the mime type module when passed a .wav file
    ✓ should response with audio/x-wav mimetype
  When using the node-cloudfiles client the mime type module when passed a .wma file
    ✓ should response with audio/x-ms-wma mimetype
  When using the node-cloudfiles client the mime type module when passed a .wmv file
    ✓ should response with video/x-ms-wmv mimetype
  When using the node-cloudfiles client the mime type module when passed a .wmx file
    ✓ should response with video/x-ms-wmx mimetype
  When using the node-cloudfiles client the mime type module when passed a .wrl file
    ✓ should response with model/vrml mimetype
  When using the node-cloudfiles client the mime type module when passed a .wsdl file
    ✓ should response with application/wsdl+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .xbm file
    ✓ should response with image/x-xbitmap mimetype
  When using the node-cloudfiles client the mime type module when passed a .xhtml file
    ✓ should response with application/xhtml+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .xls file
    ✓ should response with application/vnd.ms-excel mimetype
  When using the node-cloudfiles client the mime type module when passed a .xml file
    ✓ should response with application/xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .xpm file
    ✓ should response with image/x-xpixmap mimetype
  When using the node-cloudfiles client the mime type module when passed a .xsl file
    ✓ should response with application/xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .xslt file
    ✓ should response with application/xslt+xml mimetype
  When using the node-cloudfiles client the mime type module when passed a .yaml file
    ✓ should response with text/yaml mimetype
  When using the node-cloudfiles client the mime type module when passed a .yml file
    ✓ should response with text/yaml mimetype
  When using the node-cloudfiles client the mime type module when passed a .zip file
    ✓ should response with application/zip mimetype

♢ node-cloudfiles/storage-object

  The node-cloudfiles client when authenticated
    ✓ should return with 204
  The node-cloudfiles client the addFile() method
    ✓ should respond with true
  The node-cloudfiles client the getFile() method for a file that exists
    ✗ should return a valid StorageObject
    TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/storage-object-metadata-test.js:53:33)
    at runTest (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows.js:95:26)
    at EventEmitter.<anonymous> (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows.js:73:9)
    at EventEmitter.emit (events.js:41:20)
    at /Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/context.js:29:52
    at /Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/context.js:42:29
    at /Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/lib/cloudfiles/core.js:165:22
    at /Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/lib/cloudfiles/utils.js:156:5
    at IncomingMessage.<anonymous> (/Users/felix/.node_libraries/.npm/request/0.10.0/package/
node.js:50
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
TypeError: Cannot call method 'addMetadata' of undefined
    at Object.<anonymous> (/Library/WebServer/Documents/transloader.transload.it/apps/api2/dep/node-cloudfiles/test/storage-object-metadata-test.js:64:23)
    at run (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/suite.js:128:31)
    at EventEmitter.<anonymous> (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/suite.js:200:40)
    at EventEmitter.emit (events.js:41:20)
    at Array.<anonymous> (/Users/felix/.node_libraries/.npm/vows/0.5.2/package/lib/vows/suite.js:150:58)
    at EventEmitter._tickCallback (node.js:42:22)
    at node.js:652:9
1 (M=bccb59) felix@felix-
```

**Comment by indexzero** [comment]
Looks like I had a leftover test implementation from a previous version in storage-object-metadata-test.js. I haven't implemented the metadata APIs yet, just not enough time. So I commented out those two tests as well. 

Should work now; just pushed to 'master'. Thanks.
