### ISSUE TITLE
Path creation in Windows

### ISSUE THREAD

**Issue by hughlomas** [nodejitsu/node-cloudfiles#43]
<pre>
C:\hugh\callmonitor\node_modules\cloudfiles\vendor\mkdirp.js:22
  if (p.charAt(0) != '/') { throw new Error('Relative path: ' + p); return; }
                                  ^
Error: Relative path: C:\hugh\callmonitor\node_modules\cloudfiles\.cache\syzygy
    at mkdirPSync (C:\hugh\callmonitor\node_modules\cloudfiles\vendor\mkdirp.js:22:35)
    at Object.common.statOrMkdirp (C:\hugh\callmonitor\node_modules\cloudfiles\lib\cloudfiles\common.js:53:16)
    at new exports.Cloudfiles (C:\hugh\callmonitor\node_modules\cloudfiles\lib\cloudfiles\core.js:42:10)
    at Object.exports.createClient (C:\hugh\callmonitor\node_modules\cloudfiles\lib\cloudfiles\core.js:26:10)
    at CallSession._uploadVideoToCloud (C:\hugh\callmonitor\callsession\lib\callsession.js:129:29)
    at CallSession.end (C:\hugh\callmonitor\callsession\lib\callsession.js:105:11)
    at C:\hugh\callmonitor\callsession\lib\callsession.js:150:2
    at ChildProcess.exithandler (child_process.js:534:7)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at maybeClose (child_process.js:634:16)
</pre>

**Comment by dscape** [comment]
Remove `vendor/mkdirp.js` and replace with https://github.com/substack/node-mkdirp
