### ISSUE TITLE
Error: Invalid protocol (line 189 of main.js)

### ISSUE THREAD

**Issue by jameyg** [nodejitsu/node-cloudfiles#7]
Using the sample code from the readme below:

```
var cloudfiles = require('cloudfiles');

var config = {
    auth : {
        username: 'myusername',
        apiKey: '1a79a4d60de6718e8e5b326e338ae533'
    }
};

var client = cloudfiles.createClient(config);

// Creating a container
client.createContainer('myContainer', function (err, container) {
    // Listing files in the Container 
    container.getFiles(function (err, files) {

    });
});
```

I get this error:

```
/home/jamey/node/node_modules/cloudfiles/node_modules/request/main.js:189
  if (!options.httpModule) throw new Error("Invalid protocol");
                                 ^
Error: Invalid protocol
    at [object Object].request (/home/jamey/node/node_modules/cloudfiles/node_modules/request/main.js:189:34)
    at request (/home/jamey/node/node_modules/cloudfiles/node_modules/request/main.js:315:5)
    at makeRequest (/home/jamey/node/node_modules/cloudfiles/lib/cloudfiles/utils.js:139:5)
    at /home/jamey/node/node_modules/cloudfiles/lib/cloudfiles/utils.js:172:7
    at [object Object].callback (/home/jamey/node/node_modules/cloudfiles/lib/cloudfiles/core.js:59:7)
    at IncomingMessage.<anonymous> (/home/jamey/node/node_modules/cloudfiles/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at CleartextStream.ondata (http.js:1226:22)
    at CleartextStream._push (tls.js:303:27)
```

I dumped options at line 189, which gave me:

```
{ readable: true,
  writable: true,
  uri: 
   { protocol: 'https:',
     slashes: true,
     host: 'auth.api.rackspacecloud.com',
     hostname: 'auth.api.rackspacecloud.com',
     href: 'https://auth.api.rackspacecloud.com/v1.0',
     pathname: '/v1.0',
     port: 443 },
  headers: 
   { HOST: 'auth.api.rackspacecloud.com',
     'X-AUTH-USER': 'myusername',
     'X-AUTH-KEY': '1a79a4d60de6718e8e5b326e338ae533',
     host: 'auth.api.rackspacecloud.com' },
  callback: [Function],
  pool: {},
  dests: [],
  _redirectsFollowed: 0,
  maxRedirects: 10,
  followRedirect: true,
  method: 'GET',
  port: 443,
  host: 'auth.api.rackspacecloud.com',
  _events: { error: [Function] },
  path: '/v1.0',
  httpModule: 
   { Server: { [Function: Server] super_: [Object] },
     createServer: [Function],
     getAgent: [Function: getAgent],
     Agent: { [Function: Agent] super_: [Object] },
     request: [Function],
     get: [Function] } }
{ readable: true,
  writable: true,
  uri: { pathname: '/myContainer', href: '/myContainer' },
  method: 'PUT',
  headers: { 'X-AUTH-TOKEN': undefined, host: undefined },
  callback: [Function],
  pool: {},
  dests: [],
  _redirectsFollowed: 0,
  maxRedirects: 10,
  followRedirect: true,
  port: undefined,
  host: undefined,
  _events: { error: [Function] },
  path: '/myContainer',
  httpModule: undefined }
```

It was followed by the same error message above. I'm not experienced but I guess maybe it's not supposed to output that twice? I tried requiring the http and https modules but it didn't solve it.

**Comment by indexzero** [comment]
See if this fixes it:

``` js
var cloudfiles = require('cloudfiles');

var config = {
    auth : {
        username: 'myusername',
        apiKey: '1a79a4d60de6718e8e5b326e338ae533'
    }
};

var client = cloudfiles.createClient(config);

// Creating a container
client.setAuth(function () {
  client.createContainer('myContainer', function (err, container) {
    // Listing files in the Container 
    container.getFiles(function (err, files) {

    });
  });
});
```

**Comment by jameyg** [comment]
Trying that exact code but replacing my username and API key gives the exact same error:

```

Jameys-MacBook-Pro:rackspace jamey$ node-dev 1.js 
13 Jun 12:39:27 - [INFO] Started

/Users/jamey/rackspace/node_modules/cloudfiles/node_modules/request/main.js:189
  if (!options.httpModule) throw new Error("Invalid protocol");
                                 ^
13 Jun 12:39:28 - [ERROR] Error
Error: Invalid protocol
    at [object Object].request (/Users/jamey/rackspace/node_modules/cloudfiles/node_modules/request/main.js:189:34)
    at request (/Users/jamey/rackspace/node_modules/cloudfiles/node_modules/request/main.js:315:5)
    at makeRequest (/Users/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/utils.js:139:5)
    at Object.rackspace (/Users/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/utils.js:165:5)
    at [object Object].createContainer (/Users/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/core.js:133:9)
    at /Users/jamey/rackspace/1.js:14:10
    at [object Object].callback (/Users/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/core.js:59:7)
    at IncomingMessage.<anonymous> (/Users/jamey/rackspace/node_modules/cloudfiles/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
```

What is supposed to be set in options.httpModule? I can't figure it out. Is it the built-in http or https module or something else?

**Comment by jameyg** [comment]
Figured it out, I needed to add this line to my auth configuration:

`"host": "lon.auth.api.rackspacecloud.com"`

This is listed under the "Authentication Service" block in the readme, but it'd be more useful if it mentioned the reason behind needing this line and the differences as explained in the Cloud Files API document here under section 3.1: http://docs.rackspacecloud.com/files/api/v1/cf-devguide-20110524.pdf

Also, this error "Invalid protocol" is quite hard to debug, and only by looking at the failing tests and seeing the 401 error did it lead me to read the API documentation. Maybe better error catching somehow would help somebody who runs into this in the future (even if they should be reading the docs like me).

**Comment by jfhbrook** [comment]
I'm closing this issue because it's quite old and doesn't appear to have resulted in an exposed bug in node-cloudfiles.

If there's an issue with the examples in the README breaking, please create a new issue.
