### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by jameyg** [nodejitsu/node-cloudfiles#9]
As per the readme, I put this into the (new file) test/data/test-config.json but with my username and API key:

```
  {
    "auth": {
      "username": "your-username",
      "apiKey": "your-apikey"
    }
  }
```

I am using the latest versions of node.js and npm, 0.4.8 and 1.0.10, as of writing this on OS X, as well as installing vows using npm. When I run `vows test/*-test.js --spec` the message I get back is:

`Config file test/data/test-config.json must be created with valid data before running tests.`

Am I supposed to have more than just the six lines of the object literal given in the test-config.json file? I'm not sure what I'm doing wrong.

**Comment by jameyg** [comment]
I think I've figured it out and the tests seem to begin running now. Instead of looking in test/data/test-config.json as the readme suggests, line 22 of test/helpers.js implies it is actually looking in test/fixtures/test-config.json. After moving that file there, the tests do indeed begin to start:

```

Jameys-MacBook-Pro:cloudfiles jamey$ vows test/*-test.js --spec

♢ node-cloudfiles/authentication

  The node-cloudfiles client with a valid username and api key
    ✗ should respond with 204 and appropriate headers
      » expected 204,
    got  401 (==) // authentication-test.js:26
    ✓ should update the config with appropriate urls
  The node-cloudfiles client with an invalid username and api key
    ✓ should respond with 401

♢ node-cloudfiles/containers


node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Invalid protocol
    at [object Object].request (/Users/jamey/Shared/AllYearbooks/demos/jamey/rackspace/node_modules/cloudfiles/node_modules/request/main.js:189:34)
    at request (/Users/jamey/Shared/AllYearbooks/demos/jamey/rackspace/node_modules/cloudfiles/node_modules/request/main.js:315:5)
    at makeRequest (/Users/jamey/Shared/AllYearbooks/demos/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/utils.js:139:5)
    at Object.rackspace (/Users/jamey/Shared/AllYearbooks/demos/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/utils.js:165:5)
    at [object Object].getFiles (/Users/jamey/Shared/AllYearbooks/demos/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/core.js:194:9)
    at [object Object].destroyContainer (/Users/jamey/Shared/AllYearbooks/demos/jamey/rackspace/node_modules/cloudfiles/lib/cloudfiles/core.js:162:8)
    at Object.<anonymous> (/Users/jamey/Shared/AllYearbooks/demos/jamey/rackspace/node_modules/cloudfiles/test/container-destroy-test.js:24:18)
    at run (Jameys-MacBook-Pro:cloudfiles jamey$ 
```

So it seems the first test runs but gets an incorrect response, and the second test comes back with the same error I've been getting on issue #7.

**Comment by jameyg** [comment]
Aside from the incorrect path for the test-config.json file, the cause of the tests not running, as I explain in issue #7, is down to not including a `host` config line, to set the authentication server for RackSpace to the UK-based one.
